# Generated by Django 6.1 on 2026-08-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
